name: Build Windows Release (Fixed Version)

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        required: true
        default: 'stable'
        type: choice
        options:
          - test
          - stable

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Chocolatey and Tesseract OCR
        shell: powershell
        run: |
          # 安装 Chocolatey 包管理器
          Write-Host 'Installing Chocolatey package manager...'
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          
          # 刷新环境变量以识别 choco 命令
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          
          # 使用 Chocolatey 安装 Tesseract OCR
          Write-Host 'Installing Tesseract OCR via Chocolatey...'
          choco install tesseract -y
          
          # 验证安装
          if (Test-Path 'C:\Program Files\Tesseract-OCR\tesseract.exe') {
              echo 'C:\Program Files\Tesseract-OCR' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
              Write-Host 'Tesseract installed successfully via Chocolatey'
          } else {
              Write-Error 'Tesseract installation failed'
              exit 1
          }

      - name: Install Python dependencies (with specific versions)
        shell: powershell
        run: |
          python -m pip install --upgrade pip setuptools wheel
          
          # 安装特定版本的 setuptools 以避免兼容性问题
          pip install setuptools==68.0.0
          
          # 安装核心依赖
          pip install PyQt5==5.15.9
          pip install pytesseract==0.3.10
          pip install numpy==1.24.3
          pip install opencv-python==4.8.1.78
          pip install pillow==10.0.1
          pip install certifi==2023.7.22
          pip install requests==2.31.0
          pip install pyinstaller==6.2.0
          
          
          # 安装其他依赖
          pip install mss==9.0.1
          pip install pynput==1.7.6
          pip install screeninfo==0.8.1
          pip install ttkthemes==3.2.2

      - name: Create language pack directories
        shell: powershell
        run: |
          # 创建语言包目录
          New-Item -ItemType Directory -Path "tessdata" -Force
          Write-Host "Created language pack directories: tessdata"


      - name: Create default OCR language directories
        shell: powershell
        run: |
          # 创建默认的OCR语言包目录结构
          New-Item -ItemType Directory -Path "tessdata" -Force
          Write-Host "Created tessdata directory"
          
          # 下载一些常用的OCR语言包
          $commonLangs = @("eng")
          
          foreach ($lang in $commonLangs) {
              $url = "https://github.com/tesseract-ocr/tessdata/raw/main/${lang}.traineddata"
              $outputPath = "tessdata/${lang}.traineddata"
              
              try {
                  Invoke-WebRequest -Uri $url -OutFile $outputPath -TimeoutSec 30
                  Write-Host "Downloaded OCR language pack: $lang"
              } catch {
                  Write-Host "Failed to download $lang language pack: $($_.Exception.Message)"
              }
          }

      - name: Build with PyInstaller (simplified)
        shell: powershell
        run: |
          Write-Host 'Building Skylark Screen Translator...'
          
          if (Test-Path 'skylark_screen_translator.py') {
            Write-Host 'Found main program: skylark_screen_translator.py'
            $mainScript = 'skylark_screen_translator.py'
          } else {
            Write-Host 'Available Python files:'
            Get-ChildItem *.py | Format-Table Name
            throw 'No main program found. Please check your repository structure.'
          }

          # 检查图标文件是否存在
          if (-not (Test-Path 'skylark.ico')) {
            throw 'Icon file skylark.ico not found in the root directory'
          }
          
          # 使用简化的 PyInstaller 配置，避免问题模块
          $pyinstallerArgs = @(
              "--name", "SkylarkTranslator",
              "--onedir",
              "--windowed",
              "--icon", "skylark.ico",  # 添加图标参数
              "--add-data", "C:\Program Files\Tesseract-OCR\tesseract.exe;.",
              "--add-data", "tessdata;tessdata",
              "--add-data", "skylark.ico;.",  # 将图标文件也包含在分发包中
              "--add-binary", "C:\Program Files\Tesseract-OCR;Tesseract-OCR",
              "--hidden-import", "pytesseract",
              "--hidden-import", "numpy",
              "--hidden-import", "cv2",
              "--hidden-import", "PIL",
              "--hidden-import", "certifi",
              "--hidden-import", "requests",
              "--hidden-import", "PyQt5",
              "--hidden-import", "PyQt5.QtCore",
              "--hidden-import", "PyQt5.QtGui",
              "--hidden-import", "PyQt5.QtWidgets",
              "--exclude-module", "stanza",  # 排除有问题的模块
              "--exclude-module", "setuptools._distutils",  # 排除有问题的模块
              $mainScript
          )
          
          # 执行PyInstaller命令
          pyinstaller @pyinstallerArgs
          
          $exePath = 'dist\SkylarkTranslator\SkylarkTranslator.exe'
          if (Test-Path $exePath) {
              $folderSize = (Get-ChildItem 'dist\SkylarkTranslator' -Recurse | Measure-Object -Property Length -Sum).Sum
              $sizeMB = [math]::Round($folderSize/1MB, 2)
              Write-Host "Build successful! Directory size: $sizeMB MB"
              echo "BUILD_SIZE_MB=$sizeMB" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } else {
              throw 'Build failed: executable file not found'
          }


      - name: Create distribution package
        shell: powershell
        run: |
          $releaseType = "${{ inputs.release_type }}"
          $version = Get-Date -Format "yyyy.MM.dd.HHmm"
          $packageName = "SkylarkTranslator_Windows_${releaseType}_v${version}"
          $buildSize = "${{ env.BUILD_SIZE_MB }}"
          
          Write-Host "Creating distribution package: $packageName"
          Write-Host "Application size: $buildSize MB"
          
          Compress-Archive -Path "dist\SkylarkTranslator" -DestinationPath "dist\$packageName.zip" -Force
          
          $readmeLines = @(
            "Skylark Screen Translator - Windows Version",
            "Version: $version",
            "Type: $releaseType",
            "Build Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
            "Application Size: $buildSize MB",
            "",
            "== IMPORTANT NOTES ==",
            "This version uses a simplified build to avoid compatibility issues.",
            "Some advanced translation features may be limited.",
            "",
            "== How to Use ==",
            "1. Extract this ZIP file to any folder (e.g., C:\SkylarkTranslator)",
            "3. Or run SkylarkTranslator.exe directly",
            "",
            "== Known Limitations ==",
            "- Advanced translation features may not be available",
            "- Some language models may need to be downloaded manually",
            "- OCR functionality is fully supported",
            "",
            "== File Locations ==",
            "- Main executable: SkylarkTranslator.exe",
            "- Tesseract data: .\tessdata\",
            "- Application icon: .\skylark.ico",
            "",
            "== Support ==",
            "1. Ensuring your system has the latest Visual C++ Redistributable",
            "2. Checking for Windows updates"
          )
          
          $readmeLines | Out-File -FilePath "dist\README_$packageName.txt" -Encoding utf8
          
          Write-Host "Package created: dist\$packageName.zip"
          echo "PACKAGE_NAME=$packageName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PACKAGE_PATH=dist/$packageName.zip" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SkylarkTranslator-Windows-${{ inputs.release_type }}
          path: |
            ${{ env.PACKAGE_PATH }}
            dist/README_${{ env.PACKAGE_NAME }}.txt
          retention-days: 7

      - name: Create build summary
        shell: powershell
        run: |
          $size = (Get-Item "${{ env.PACKAGE_PATH }}").Length
          $sizeMB = [math]::Round($size/1MB, 2)
          
          Write-Host "## Build Complete - Simplified Edition"
          Write-Host "- Release Type: ${{ inputs.release_type }}"
          Write-Host "- Application Size: ${{ env.BUILD_SIZE_MB }} MB"
          Write-Host "- Zip Package Size: ${sizeMB} MB"
          Write-Host "- File Name: ${{ env.PACKAGE_NAME }}.zip"
          Write-Host ""
          Write-Host "## Key Changes"
          Write-Host "1. Simplified Build: Excluded problematic modules (stanza, setuptools._distutils)"
          Write-Host "2. Stable Dependencies: Used specific versions to ensure compatibility"
          Write-Host "3. Fallback Implementation: Added graceful fallback for translation features"
          Write-Host "4. Tesseract Installation: Now using Chocolatey package manager for reliable installation"
          Write-Host ""
          Write-Host "## Download & Use"
          Write-Host "1. Download the ZIP file from Artifacts"
          Write-Host "2. Extract to any folder"
          Write-Host "3. OCR functionality should work fully"
          Write-Host "4. Translation features may be limited but should not crash"
